### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by lorirava** [fod-dev/fod-uploader-java#100]
**Environment:**

- GitLab Runner
- image: maven:3.6.3-openjdk-14 
- FoDUpload installed via https://raw.githubusercontent.com/fortify/FortifyToolsInstaller/v2/FortifyToolsInstaller.sh 

**Command:**

```
FoDUpload -z package.zip -aurl "$FOD_API_URL" -purl "$FOD_URL" -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USERNAME" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "Submitted from GitLab Pipeline"
```
**Log:**

```
$ FoDUpload -z package.zip -aurl "$FOD_API_URL" -purl "$FOD_URL" -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USERNAME" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "Submitted from GitLab Pipeline"
Authenticating
Authenticated
Beginning upload
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.fortify.fod.fodapi.controllers.StaticScanController.StartStaticScan(StaticScanController.java:121)
	at com.fortify.fod.Main.main(Main.java:117)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 6 more
Retiring Token : Token Retired Successfully
```

**Comment by nikhil888-teach** [comment]
![image](https://user-images.githubusercontent.com/84656107/173507540-e1304ebf-ffd8-4eed-9af3-c2365ef2c8b3.png)


I have a same problem.
you have any solution ?

**Comment by lorirava** [comment]
I've contected the fortify support. It seems a problem in the RELEASE. the only possible solution was delete the release and create a new one.

**Comment by iamraajkanchan** [comment]
Has the new release being created?

**Comment by nikhil888-teach** [comment]
NO

**Comment by saqibskvip** [comment]
It's Worked thanks
