### ISSUE TITLE
obtuse FOD error when incorrect entitlement selected for fod uploader scan start

### ISSUE THREAD

**Issue by SamShober** [fod-dev/fod-uploader-java#25]
Customer was trying to work on build integration from a linux environment but the scan start was failing immediately after upload with an obtuse error (see red text below).  It took some debugging but we figured it out. 

Issue:  when using FODUploader to start a scan of an application that has already been scanned its important that the entitlement period attribute (-ep) use the same type as the type previously used if the entitlement is active.  In our case the app had been started with a subscription several weeks earlier. The user was specifying “–ep 1” which is single scan instead of “-ep 2” subscription.  The portal backend saw that, decided it was a conflict and threw a NullPointerException instead of a more useful error message. 

[commandprompt] $ java -jar /home/{username}/HP_Fortify/FodUpload.jar -uc 'name' 'pass’ -z /home/{username}/tmp/{zipfilename}.zip -bsi eyJwer5hbnRJZCI6MTQ3NCwidGVuYW50Q29kZSI6IlBPVl9UcmF2ZWxwb3J0IiwicmVsZWFzZUlkIjoxMzYzNjIsInBheWxvYWRUeXBlIjoiQU5BTFlTSVNfUEFZTE9BRCIsImFzcwsec21lbnRUeXBlSWQiOjI4MCwidGVjaG5vbG9neVR5cGUiOiJQWVRIT04iLCJ0ZWNobm9sb2d5VHlwZUlkIjoxMCwidGVjaG5vbG9neVZlcnNpb24iOiJTdGFuZGFyZCBQeXRob24iLCJ0ZWNobm9sb2d5VmVyc2lvbklkIjoxMywiYXVkaXRQcmVmZXJlbmNlIjoiQXV0b21hdGVkIiwiYXVkaXRQcmVmZXJlbmNlSWQiOjIsImluY2x1ZGVUaGlyZFBhcnR5IjpmYWxzZSwiaW5jbHVkZU9wZW5Tb3VyY2VBbmFseXNpcyI6ZmFsc2UsInNjYW5QcmVmZXJlbmNlIjoiMCIsInNjYW5QcmVmZXJlbmNlSWQiOjAsInBvcnRhbFVyaSI6Imh0dHBzOi8vYW1zLmZvcnRpZnkuY29tIiwiYXBpVXJpIjoiaHR0cHM6Ly9hcGkuYW1zLmZvcnRpZnkuY29tIn0=  -ep 1 -P http://{proxy address}:8080
Authenticating
Beginning upload
java.lang.NullPointerException
at com.fortify.fod.fodapi.controllers.StaticScanController.StartStaticScan(StaticScanController.java:53)
at com.fortify.fod.Main.main(Main.java:66)
Retiring Token : Token Retired Successfully

Once the user changed –ep 1 to –ep 2 the upload w2as successful and the scan successfully started, validating the script worked and they could then proceed with build integrations for the specific application.

**Comment by mtgibbs** [comment]
The NullPointerException would have occured in the software locally.  What version did they run when they saw this?  It looks like a valid entitlement (assessment type) didn't get returned from the API.

**Comment by AlexanderSkogorev** [comment]
We had the same issue. The issue was about our subscription. We created new application and our existing subscription did not cover separate application. The error was the same, and -ep parameter was set to Subscription.
