### ISSUE TITLE
Invalid entitlement/assessment type

### ISSUE THREAD

**Issue by rageshns** [fod-dev/fod-uploader-java#32]
java -jar FodUpload.jar -ep Subscription -z ABC.zip -ac vvvvvvvv 'dddddddd' -u 'https://api.ams.fortify.com/bsi2.aspx?tid=123&tc=Carnival&pv=12345&payloadType=ANALYSIS_PAYLOAD&astid=120&ts=JAVA%2fJ2EE&ll=1.7'
Authenticating
Beginning upload
java.lang.Exception: Invalid entitlement/assessment type
valid entitlement/assessment type
	at com.fortify.fod.fodapi.controllers.StaticScanController.StartStaticScan(StaticScanController.java:50)
	at com.fortify.fod.Main.main(Main.java:66)

**Comment by mtgibbs** [comment]
It's likely that your entitlement is not correct or active.  Is your entitlement for single scan or subscription?

**Comment by Zilioli** [comment]
I'm having the same problem. Does anyone have an idea?
